# Generated by Django 6.0.6 on 2026-07-12 07:20

import django.db.models.deletion
import django.db.models.query
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_category_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orders.table')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.query.prefetch_related_objects, related_name='order_item', to='orders.menuitem')),
            ],
        ),
    ]
