# Generated by Django 6.0.6 on 2026-07-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_order_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'preparing'), ('r', 'Ready'), ('s', 'Served'), ('b', 'Billed')], default='p', max_length=2),
        ),
    ]
