# Generated by Django 6.0.6 on 2026-07-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('p', 'preparing'), ('r', 'Ready'), ('s', 'Served')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('PS', 'Partially_served'), ('s', 'Served'), ('b', 'Billed')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('PS', 'Partially_served'), ('s', 'Served'), ('b', 'Billed')]),
        ),
    ]
