# Generated by Django 6.0.6 on 2026-07-18 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_kitchen_station_menuitem_default_priority_and_more'),
    ]

    operations = [

        # Rename KITCHEN_STATION model to KitchenStation
        migrations.RenameModel(
            old_name='KITCHEN_STATION',
            new_name='KitchenStation',
        ),


        # Update estimated preparation time field
        migrations.AlterField(
            model_name='menuitem',
            name='est_time',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text='Estimated preparation time in minutes'
            ),
        ),


        # Update station foreign key
        migrations.AlterField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='menu_items',
                to='orders.kitchenstation',
            ),
        ),


        # Update Order status field
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('p', 'Pending'),
                    ('ps', 'Partially Served'),
                    ('s', 'Served'),
                    ('b', 'Billed')
                ],
                default='p',
                max_length=2,
            ),
        ),


        # Update Order table relation
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='orders',
                to='orders.table',
            ),
        ),


        # Update OrderHistory status
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(
                choices=[
                    ('p', 'Pending'),
                    ('ps', 'Partially Served'),
                    ('s', 'Served'),
                    ('b', 'Billed')
                ],
                max_length=2,
            ),
        ),


        # Update OrderItem price
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),


        # Update OrderItem quantity
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(
                default=1
            ),
        ),


        # Update OrderItem status
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(
                choices=[
                    ('p', 'Preparing'),
                    ('r', 'Ready'),
                    ('s', 'Served')
                ],
                default='p',
                max_length=2,
            ),
        ),


        # Update Table reserved field
        migrations.AlterField(
            model_name='table',
            name='is_reserved',
            field=models.BooleanField(
                default=False
            ),
        ),
    ]